<div id="main">
	<h1>Login to your account</h1>
	<?php
	if(isset($this->errors)){
		$this->Errors($this->errors);
	}
	?>
	<?php echo $this->form; ?>
	<h3>
		Did you forget your password? Click <a
			href="<?php echo $this->url(array('controller'=>'account','action'=>'lost'));?>">here
			to retrieve it</a>.
	</h3>
</div>
<div id="sidebar">
	<h1>Useful Notes</h1>
	<ul>
		<li>Not an account owner? You can click <a href="register.php">here to
				register</a>
		</li>
		<li>Make sure to NEVER give away your account details. We would never
			ask for them!</li>
		<li>Having connectivity issues? You can <a href="contact.php">send us
				an email.</a>
		</li>
	</ul>
</div>

<p class="clear" />